%YAML 1.1
---
language: en
pipeline: supervised_embeddings
policies:
- name: MemoizationPolicy
- name: KerasPolicy
- name: MappingPolicy
- core_threshold: 0.5
  fallback_action_name: utter_default
  name: FallbackPolicy
  nlu_threshold: 0.7
